language: r
dist: bionic
cache: packages

matrix:
  include:
  - r: devel
    os: linux
  - r: release
    os: linux
  - r: release
    os: osx

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - ropensci/spelling

before_install:
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install imagemagick@6; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Check dead links
  #- sudo apt-get install -qq npm
  #- npm config set strict-ssl false
  #- sudo npm install -g markdown-link-check

before_script:
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz

after_script:
  - Rscript -e "remotes::install_github(\"richelbilderbeek/aureole\")"
  - Rscript -e "knitr::kable(aureole::download_image_urls_from_name(\"Homo sapiens\"))"

after_success:
  - travis_wait 60 Rscript -e 'covr::codecov()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  # Check dead links
  #- rm .travis.yml
  #- ./scripts/check_dead_links || true
